version: '3.9'
services:
  award:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh -c 'yarn install --frozen-lockfile && yarn start:dev'
    container_name: golden-raspberry-awards-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules
